# Config file for automatic testing at travis-ci.org

language: python
# Python 3.7 works only in Xenial with sudo
# https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
dist: xenial
sudo: yes

python:
  - '3.7'
  - '3.6'
  - '2.7'
  - 'pypy'

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
    - pip install flake8

# command to run tests, e.g. python setup.py test
script:
    - flake8
    - python setup.py test
